<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite thread-count="4" guice-stage="DEVELOPMENT" name="Failed suite [Calculator (0)]" parallel="methods">
  <test thread-count="4" name="Trigonometric(failed)" parallel="methods">
    <classes>
      <class name="com.epam.tat.module4.TrigonometricFunctionality.TgTest">
        <methods>
          <include name="initCalculator"/>
          <include name="TgTest" invocation-numbers="1"/>
        </methods>
      </class> <!-- com.epam.tat.module4.TrigonometricFunctionality.TgTest -->
      <class name="com.epam.tat.module4.TrigonometricFunctionality.SinTest">
        <methods>
          <include name="initCalculator"/>
          <include name="SinTest" invocation-numbers="0"/>
        </methods>
      </class> <!-- com.epam.tat.module4.TrigonometricFunctionality.SinTest -->
      <class name="com.epam.tat.module4.TrigonometricFunctionality.CosTest">
        <methods>
          <include name="initCalculator"/>
          <include name="CosTest" invocation-numbers="0 1 2"/>
        </methods>
      </class> <!-- com.epam.tat.module4.TrigonometricFunctionality.CosTest -->
    </classes>
  </test> <!-- Trigonometric(failed) -->
</suite> <!-- Failed suite [Calculator (0)] -->
